### ISSUE TITLE
Loading indicator shows infinity

### ISSUE THREAD

**Issue by kikuchiharuma** [uniba/circuitlab-team#4]
<img width="1338" alt="Screenshot 2024-07-23 at 21 00 48" src="https://github.com/user-attachments/assets/a33af5e7-796a-4bc4-92f5-26747a4b8f2a">

**Comment by akisoqls** [comment]
The cause of the issue may be due to the fact that netlify is not returning header includes `"Content-Length"`.

The `onProgress1` and `onProgress2` functions in the public/js/js.js are passed to the THREE.ColladaLoader().load() function as the 3rd arg.

https://github.com/uniba/circuitlab-team/blob/a725449ee2a3b0883e17b62f8a4a2b043d4b22da/public/js/js.js#L133

https://github.com/uniba/circuitlab-team/blob/a725449ee2a3b0883e17b62f8a4a2b043d4b22da/public/js/js.js#L131

`THREE.ColladaLoader().load()` passes an object that includes the `total` key to the function of the 3rd arg. The source of the `total` key is value of the `request.getResponseHeader( "Content-Length" )` of the .dae file. But now, `request.getResponseHeader( "Content-Length" )` is returning `null` because netlify does not return a header that includes `"Content-Length"`.

https://github.com/uniba/circuitlab-team/blob/a725449ee2a3b0883e17b62f8a4a2b043d4b22da/public/lib/loaders/ColladaLoader.js#L98-L104

The arg of `onProgress1` and `onProgress2` named `callback` includes `total` key and `loaded` key. The object is passed from `THREE.ColladaLoader().load()`. The value of `total` is `null` because `request.getResponseHeader( "Content-Length" )` is returning `null`. As a result, the `onProgress1` and `onProgress2` executes `callback.loaded / null`  and outputs `Infinity`.

https://github.com/uniba/circuitlab-team/blob/a725449ee2a3b0883e17b62f8a4a2b043d4b22da/public/js/js.js#L52-L56

So, I think add a settings to the netlify.toml file so that netlify returns a header that includes "Content-Length" will fix the issue.

**Comment by akisoqls** [comment]
I will send pull request of netlify.toml later.

**Comment by akisoqls** [comment]
I sent pull request #7

**Comment by akisoqls** [comment]
Fix at 79079939841686f92075b640bde4149de25956af
